name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macOS-latest
          - macOS-11
        raku-version:
          - 'latest'
          - '2022.02'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: macOS specific setup
        if: contains(matrix.os, 'macOS')
        run: |
            brew update
            brew install libxml2
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install --deps-only .
      - name: Run Tests
        run: prove6 -I. t xt
